In [3]:
import numpy as np

def arr(a):
    print("Los puntos que desea evaluar en la funcion son:")
    print(a)

def Hermite(x, y, der, p):
    n = len(x)
    
    # Inicializamos la matriz de diferencias divididas
    dif_div = np.zeros((n, n))

    # Llenamos la primera columna con los valores de y
    for i in range(n):
        dif_div[i, 0] = y[i]

    # Calculamos las diferencias divididas
    for j in range(1, n):
        for i in range(n-1, j-1, -1):
            dif_div[i, j] = (dif_div[i, j-1] - dif_div[i-1, j-1]) / (x[i] - x[i-j])

    # Calculamos el término de Hermite
    res = dif_div[0, 0]
    prod_termin = 1

    for i in range(1, n):
        prod_termin *= (p - x[i-1])
        res += dif_div[i, i] * prod_termin

    return res

if __name__ == "__main__":
    pInter = float(input("Ingrese el punto que desea interpolar: "))

    n = int(input("Numero de puntos que se conocen: "))
    x = np.zeros(n)
    y = np.zeros(n)
    deriv = np.zeros(n)

    for i in range(n):
        x[i] = float(input(f"Ingrese el punto {i+1} que quiere evaluar en la funcion: "))

    print()

    for i in range(n):
        y[i] = float(input(f"Ingrese el valor del punto {i+1} evaluado en la funcion (f(x) o y): "))

    print()

    for i in range(n):
        deriv[i] = float(input(f"Ingrese el valor de la derivada del punto (f'(x)) {i+1}: "))

    print()

    arr(x)
    arr(y)
    arr(deriv)

    p = Hermite(x, y, deriv, pInter)

    print(f"\nEl valor interpolado en x = {pInter} es: {p}\n")





Los puntos que desea evaluar en la funcion son:
[1.3 1.6 1.9]
Los puntos que desea evaluar en la funcion son:
[0.620086  0.4554022 0.2818816]
Los puntos que desea evaluar en la funcion son:
[-0.5220232 -0.5698959 -0.5811571]

El valor interpolado en x = 1.5 es: 0.5112786666666667

